import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import BudgetPieChart from '../components/BudgetPieChart';
import Spinner from '../components/Spinner';

export default function SharePage() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  const loadSharedTrip = async () => {
    try {
      const res = await fetch(`http://localhost:5000/api/trips/${id}/share`);
      if (!res.ok) {
        throw new Error('Failed to load shared trip');
      }
      const json = await res.json();
      // Handle standard wrapped or direct trip objects
      const tripData = json.trip || json;
      if (tripData && tripData.destination) {
        setData(tripData);
      } else {
        setData(null);
      }
    } catch (err) {
      toast.error('Failed to fetch shared trip details');
      setData(null);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    document.title = "Planora — Shared Trip";
    loadSharedTrip();
  }, [id]);

  if (loading) {
    return (
      <div className="loading-page">
        <Spinner />
      </div>
    );
  }

  if (!data) {
    return (
      <div 
        style={{ 
          textAlign: 'center', 
          padding: '6rem 2rem', 
          backgroundColor: 'var(--bg-primary)', 
          minHeight: '100vh', 
          display: 'flex', 
          flexDirection: 'column', 
          justifyContent: 'center', 
          alignItems: 'center' 
        }}
      >
        <h2 style={{ color: 'var(--text-primary)', marginBottom: '1.5rem' }}>Shared trip not found</h2>
        <button onClick={() => navigate('/')} className="btn btn-primary">
          Go back to Home
        </button>
      </div>
    );
  }

  return (
    <div style={{ background: 'var(--bg-primary)', minHeight: '100vh', color: 'var(--text-primary)' }}>
      
      {/* Share Navigation Bar */}
      <nav className="share-navbar">
        <span className="logo" onClick={() => navigate('/')} style={{ cursor: 'pointer' }}>
          ✈️ Planora
        </span>
        <button onClick={() => navigate('/signup')} className="btn btn-primary">
          Plan Your Own Trip
        </button>
      </nav>

      {/* Share Page Body */}
      <div className="share-page">
        <div className="share-container">

          {/* Header */}
          <div className="share-header">
            <h1>{data.destination}</h1>
            <div className="trip-badges">
              <span className="info-badge">📅 {data.days} Days</span>
              <span className="info-badge">👥 {data.travelers || 1} Travelers</span>
            </div>
            <p className="generated-by">Generated by Planora ✨</p>
          </div>

          {/* Itinerary Timeline & Sidebar Budget */}
          <div className="result-grid">
            
            {/* Itinerary Timeline */}
            <div className="itinerary-col">
              {data.userEditedItinerary?.days?.map((day) => (
                <div key={day.dayNumber} className="day-card">
                  <h3 className="day-title">Day {day.dayNumber}</h3>
                  <div className="slots-list">
                    {day.slots.map((slot) => {
                      const isPlace = !!slot.place;
                      return (
                        <div key={slot.slotId} className={`slot-card ${!isPlace ? 'empty-slot' : ''}`}>
                          <span className={`time-badge time-${slot.time.toLowerCase()}`}>
                            {slot.time}
                          </span>
                          
                          <div className="slot-content">
                            {isPlace ? (
                              <>
                                <h4>{slot.place.name}</h4>
                                <span className="category-badge">{slot.place.category}</span>
                                <div className="slot-meta">
                                  <span>₹{slot.place.estimatedCost}</span>
                                  <span>{slot.place.timeRequired} hrs</span>
                                </div>
                                <p className="slot-description">
                                  {slot.place.description || 'No description available'}
                                </p>
                              </>
                            ) : (
                              <p className="empty-text">Free time 🌅</p>
                            )}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>

            {/* Sidebar Column */}
            <div className="sidebar-col">
              <div className="sidebar-card">
                <h3>Budget Summary</h3>
                <BudgetPieChart data={data.budgetBreakdown} />
                
                <div className="budget-list">
                  <div className="budget-divider"></div>
                  <div className="budget-row total">
                    <span>Total Spent</span>
                    <span>₹{data.budgetBreakdown?.total || 0}</span>
                  </div>
                  <div className={`budget-row ${(data.budgetBreakdown?.remaining || 0) >= 0 ? 'positive' : 'negative'}`}>
                    <span>Remaining</span>
                    <span>₹{data.budgetBreakdown?.remaining || 0}</span>
                  </div>
                </div>
              </div>
            </div>

          </div>

          {/* CTA Banner */}
          <div className="share-cta">
            <h2>Want a trip like this?</h2>
            <p>Plan yours free on Planora</p>
            <button onClick={() => navigate('/signup')} className="btn btn-primary">
              Start Planning
            </button>
          </div>

        </div>
      </div>
      
    </div>
  );
}
